CREATE TABLE IF NOT EXISTS `pay_app` (
                                         `id` BIGINT NOT NULL AUTO_INCREMENT,
                                         `app_key` VARCHAR(64) NOT NULL,
                                         `name` VARCHAR(64) NOT NULL,
                                         `status` TINYINT NOT NULL,
                                         `remark` VARCHAR(255) DEFAULT NULL,
                                         `order_notify_url` VARCHAR(1024) NOT NULL,
                                         `refund_notify_url` VARCHAR(1024) NOT NULL,
                                         `creator` VARCHAR(64) DEFAULT '',
                                         `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                         `updater` VARCHAR(64) DEFAULT '',
                                         `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                         `deleted` BIT(1) NOT NULL DEFAULT FALSE,
                                         `tenant_id` BIGINT NOT NULL DEFAULT 0,
                                         PRIMARY KEY (`id`)
) COMMENT = '支付应用';

CREATE TABLE IF NOT EXISTS `pay_channel` (
                                             `id` BIGINT NOT NULL AUTO_INCREMENT,
                                             `code` VARCHAR(32) NOT NULL,
                                             `status` TINYINT NOT NULL,
                                             `remark` VARCHAR(255) DEFAULT NULL,
                                             `fee_rate` DOUBLE NOT NULL DEFAULT 0,
                                             `app_id` BIGINT NOT NULL,
                                             `config` VARCHAR(10240) NOT NULL,
                                             `creator` VARCHAR(64) DEFAULT '',
                                             `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                             `updater` VARCHAR(64) DEFAULT '',
                                             `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                             `deleted` BIT(1) NOT NULL DEFAULT FALSE,
                                             `tenant_id` BIGINT NOT NULL DEFAULT 0,
                                             PRIMARY KEY (`id`)
) COMMENT = '支付渠道';

CREATE TABLE IF NOT EXISTS `pay_order` (
                                           `id` BIGINT NOT NULL AUTO_INCREMENT,
                                           `app_id` BIGINT NOT NULL,
                                           `channel_id` BIGINT DEFAULT NULL,
                                           `channel_code` VARCHAR(32) DEFAULT NULL,
                                           `merchant_order_id` VARCHAR(64) NOT NULL,
                                           `subject` VARCHAR(32) NOT NULL,
                                           `body` VARCHAR(128) NOT NULL,
                                           `notify_url` VARCHAR(1024) NOT NULL,
                                           `price` BIGINT NOT NULL,
                                           `channel_fee_rate` DOUBLE DEFAULT 0,
                                           `channel_fee_price` BIGINT DEFAULT 0,
                                           `status` TINYINT NOT NULL,
                                           `user_ip` VARCHAR(50) NOT NULL,
                                           `expire_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                           `success_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
                                           `notify_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
                                           `extension_id` BIGINT DEFAULT NULL,
                                           `no` VARCHAR(64) DEFAULT NULL,
                                           `refund_price` BIGINT NOT NULL,
                                           `channel_user_id` VARCHAR(255) DEFAULT NULL,
                                           `channel_order_no` VARCHAR(64) DEFAULT NULL,
                                           `creator` VARCHAR(64) DEFAULT '',
                                           `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                           `updater` VARCHAR(64) DEFAULT '',
                                           `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                           `deleted` BIT(1) NOT NULL DEFAULT FALSE,
                                           PRIMARY KEY (`id`)
) COMMENT = '支付订单';

CREATE TABLE IF NOT EXISTS `pay_order_extension` (
                                                     `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                     `no` VARCHAR(64) NOT NULL,
                                                     `order_id` BIGINT NOT NULL,
                                                     `channel_id` BIGINT NOT NULL,
                                                     `channel_code` VARCHAR(32) NOT NULL,
                                                     `user_ip` VARCHAR(50) DEFAULT NULL,
                                                     `status` TINYINT NOT NULL,
                                                     `channel_extras` VARCHAR(1024) DEFAULT NULL,
                                                     `channel_error_code` VARCHAR(64) DEFAULT NULL,
                                                     `channel_error_msg` VARCHAR(64) DEFAULT NULL,
                                                     `channel_notify_data` VARCHAR(1024) DEFAULT NULL,
                                                     `creator` VARCHAR(64) DEFAULT '',
                                                     `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                     `updater` VARCHAR(64) DEFAULT '',
                                                     `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                     `deleted` BIT(1) NOT NULL DEFAULT FALSE,
                                                     PRIMARY KEY (`id`)
) COMMENT = '支付订单拓展';

CREATE TABLE IF NOT EXISTS `pay_refund` (
                                            `id` BIGINT NOT NULL AUTO_INCREMENT,
                                            `no` VARCHAR(64) NOT NULL,
                                            `app_id` BIGINT NOT NULL,
                                            `channel_id` BIGINT NOT NULL,
                                            `channel_code` VARCHAR(32) NOT NULL,
                                            `order_id` BIGINT NOT NULL,
                                            `order_no` VARCHAR(64) NOT NULL,
                                            `merchant_order_id` VARCHAR(64) NOT NULL,
                                            `merchant_refund_id` VARCHAR(64) NOT NULL,
                                            `notify_url` VARCHAR(1024) NOT NULL,
                                            `status` TINYINT NOT NULL,
                                            `pay_price` BIGINT NOT NULL,
                                            `refund_price` BIGINT NOT NULL,
                                            `reason` VARCHAR(256) NOT NULL,
                                            `user_ip` VARCHAR(50) DEFAULT NULL,
                                            `channel_order_no` VARCHAR(64) NOT NULL,
                                            `channel_refund_no` VARCHAR(64) DEFAULT NULL,
                                            `success_time` DATETIME DEFAULT NULL,
                                            `channel_error_code` VARCHAR(128) DEFAULT NULL,
                                            `channel_error_msg` VARCHAR(256) DEFAULT NULL,
                                            `channel_notify_data` VARCHAR(1024) DEFAULT NULL,
                                            `creator` VARCHAR(64) DEFAULT '',
                                            `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                            `updater` VARCHAR(64) DEFAULT '',
                                            `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                            `deleted` BIT(1) NOT NULL DEFAULT FALSE,
                                            PRIMARY KEY (`id`)
) COMMENT = '退款订单';

CREATE TABLE IF NOT EXISTS `pay_notify_task` (
                                                 `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                 `app_id` BIGINT NOT NULL,
                                                 `type` TINYINT NOT NULL,
                                                 `data_id` BIGINT NOT NULL,
                                                 `merchant_order_id` VARCHAR(64) NOT NULL,
                                                 `status` TINYINT NOT NULL,
                                                 `next_notify_time` DATETIME DEFAULT NULL,
                                                 `last_execute_time` DATETIME DEFAULT NULL,
                                                 `notify_times` INT NOT NULL,
                                                 `max_notify_times` INT NOT NULL,
                                                 `notify_url` VARCHAR(1024) NOT NULL,
                                                 `creator` VARCHAR(64) DEFAULT '',
                                                 `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                 `updater` VARCHAR(64) DEFAULT '',
                                                 `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                 `deleted` BIT(1) NOT NULL DEFAULT FALSE,
                                                 `tenant_id` BIGINT NOT NULL DEFAULT 0,
                                                 PRIMARY KEY (`id`)
) COMMENT = '支付通知任务';

CREATE TABLE IF NOT EXISTS `pay_notify_log` (
                                                `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                `task_id` BIGINT NOT NULL,
                                                `notify_times` INT NOT NULL,
                                                `response` VARCHAR(1024) NOT NULL,
                                                `status` TINYINT NOT NULL,
                                                `creator` VARCHAR(64) DEFAULT '',
                                                `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                `updater` VARCHAR(64) DEFAULT '',
                                                `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                `deleted` BIT(1) NOT NULL DEFAULT FALSE,
                                                PRIMARY KEY (`id`)
) COMMENT = '支付通知日志';


CREATE TABLE IF NOT EXISTS `pay_wallet_recharge_package` (
                                                             `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
                                                             `name` VARCHAR(255) NOT NULL COMMENT '套餐名',
                                                             `pay_price` INT NOT NULL COMMENT '支付金额',
                                                             `bonus_price` INT NOT NULL COMMENT '赠送金额',
                                                             `status` TINYINT NOT NULL COMMENT '状态',
                                                             `creator` VARCHAR(64) DEFAULT '' COMMENT '创建者',
                                                             `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                                             `updater` VARCHAR(64) DEFAULT '' COMMENT '更新者',
                                                             `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                                             `deleted` BIT(1) NOT NULL DEFAULT FALSE COMMENT '是否删除',
                                                             `tenant_id` BIGINT NOT NULL DEFAULT 0,
                                                             PRIMARY KEY (`id`)
) COMMENT '钱包充值套餐';

CREATE TABLE IF NOT EXISTS `pay_wallet` (
                                            `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
                                            `user_id` BIGINT NOT NULL COMMENT '用户 id',
                                            `user_type` INT NOT NULL COMMENT '用户类型',
                                            `balance` INT NOT NULL COMMENT '余额，单位分',
                                            `freeze_price` INT NOT NULL COMMENT '冻结金额，单位分',
                                            `total_expense` INT NOT NULL COMMENT '累计支出，单位分',
                                            `total_recharge` INT NOT NULL COMMENT '累计充值，单位分',
                                            `creator` VARCHAR(64) DEFAULT '' COMMENT '创建者',
                                            `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                            `updater` VARCHAR(64) DEFAULT '' COMMENT '更新者',
                                            `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                            `deleted` BIT(1) NOT NULL DEFAULT FALSE COMMENT '是否删除',
                                            `tenant_id` BIGINT NOT NULL DEFAULT 0,
                                            PRIMARY KEY (`id`)
) COMMENT '支付钱包';

CREATE TABLE IF NOT EXISTS `pay_transfer` (
                                              `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
                                              `no` VARCHAR(255) NOT NULL COMMENT '转账单号',
                                              `app_id` BIGINT NOT NULL COMMENT '应用编号',
                                              `channel_id` BIGINT NOT NULL COMMENT '转账渠道编号',
                                              `channel_code` VARCHAR(255) NOT NULL COMMENT '转账渠道编码',
                                              `merchant_transfer_id` VARCHAR(255) NOT NULL COMMENT '商户转账单编号',
                                              `type` INT NOT NULL COMMENT '类型',
                                              `subject` VARCHAR(255) NOT NULL COMMENT '转账标题',
                                              `price` INT NOT NULL COMMENT '转账金额，单位：分',
                                              `user_name` VARCHAR(255) NOT NULL COMMENT '收款人姓名',
                                              `status` INT NOT NULL COMMENT '转账状态',
                                              `success_time` DATETIME NULL COMMENT '订单转账成功时间',
                                              `alipay_logon_id` VARCHAR(255) NULL COMMENT '支付宝登录号',
                                              `openid` VARCHAR(255) NULL COMMENT '微信 openId',
                                              `notify_url` VARCHAR(255) NULL COMMENT '异步通知地址',
                                              `user_ip` VARCHAR(255) NULL COMMENT '用户 IP',
                                              `channel_extras` TEXT NULL COMMENT '渠道的额外参数',
                                              `channel_transfer_no` VARCHAR(255) NULL COMMENT '渠道转账单号',
                                              `channel_error_code` VARCHAR(255) NULL COMMENT '调用渠道的错误码',
                                              `channel_error_msg` VARCHAR(255) NULL COMMENT '调用渠道的错误提示',
                                              `channel_notify_data` TEXT NULL COMMENT '渠道的同步/异步通知的内容',
                                              `creator` VARCHAR(64) DEFAULT '' COMMENT '创建者',
                                              `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                              `updater` VARCHAR(64) DEFAULT '' COMMENT '更新者',
                                              `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                              `deleted` BIT(1) NOT NULL DEFAULT FALSE COMMENT '是否删除',
                                              PRIMARY KEY (`id`)
) COMMENT '转账单';