CREATE TABLE IF NOT EXISTS `mp_account` (
                                            `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
                                            `tenant_id` BIGINT NOT NULL COMMENT '租户编号',
                                            `name` VARCHAR(255) NOT NULL COMMENT '公众号名称',
                                            `account` VARCHAR(255) NOT NULL COMMENT '公众号账号',
                                            `app_id` VARCHAR(255) NOT NULL COMMENT '公众号 appid',
                                            `app_secret` VARCHAR(255) NOT NULL COMMENT '公众号密钥',
                                            `token` VARCHAR(255) NOT NULL COMMENT '公众号token',
                                            `aes_key` VARCHAR(255) NOT NULL COMMENT '消息加解密密钥',
                                            `qr_code_url` VARCHAR(255) COMMENT '二维码图片 URL',
                                            `remark` VARCHAR(255) COMMENT '备注',
                                            `creator` VARCHAR(64) DEFAULT '' COMMENT '创建者',
                                            `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                            `updater` VARCHAR(64) DEFAULT '' COMMENT '更新者',
                                            `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                            `deleted` BIT(1) NOT NULL DEFAULT FALSE COMMENT '是否删除',
                                            PRIMARY KEY (`id`)
) COMMENT '公众号账号';


CREATE TABLE IF NOT EXISTS `mp_material` (
                                             `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
                                             `account_id` BIGINT NOT NULL COMMENT '公众号账号的编号',
                                             `app_id` VARCHAR(255) NOT NULL COMMENT '公众号 appId',
                                             `media_id` VARCHAR(255) NOT NULL COMMENT '公众号素材 id',
                                             `type` VARCHAR(50) NOT NULL COMMENT '文件类型',
                                             `permanent` BIT(1) NOT NULL COMMENT '是否永久',
                                             `url` VARCHAR(255) COMMENT '文件服务器的 URL',
                                             `name` VARCHAR(255) COMMENT '名字',
                                             `mp_url` VARCHAR(255) COMMENT '公众号文件 URL',
                                             `title` VARCHAR(255) COMMENT '视频素材的标题',
                                             `introduction` VARCHAR(255) COMMENT '视频素材的描述',
                                             `creator` VARCHAR(64) DEFAULT '' COMMENT '创建者',
                                             `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                             `updater` VARCHAR(64) DEFAULT '' COMMENT '更新者',
                                             `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                             `deleted` BIT(1) NOT NULL DEFAULT FALSE COMMENT '是否删除',
                                             PRIMARY KEY (`id`)
) COMMENT '公众号素材';


CREATE TABLE IF NOT EXISTS `mp_menu` (
                                         `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
                                         `account_id` BIGINT NOT NULL COMMENT '公众号账号的编号',
                                         `app_id` VARCHAR(255) NOT NULL COMMENT '公众号 appId',
                                         `name` VARCHAR(255) NOT NULL COMMENT '菜单名称',
                                         `menu_key` VARCHAR(255) NOT NULL COMMENT '菜单标识',
                                         `parent_id` BIGINT NOT NULL COMMENT '父菜单编号',
                                         `type` VARCHAR(50) COMMENT '按钮类型',
                                         `url` VARCHAR(1024) COMMENT '网页链接',
                                         `mini_program_app_id` VARCHAR(255) COMMENT '小程序的 appId',
                                         `mini_program_page_path` VARCHAR(255) COMMENT '小程序的页面路径',
                                         `article_id` VARCHAR(255) COMMENT '跳转图文的媒体编号',
                                         `reply_message_type` VARCHAR(50) COMMENT '消息类型',
                                         `reply_content` TEXT COMMENT '回复的消息内容',
                                         `reply_media_id` VARCHAR(255) COMMENT '回复的媒体 id',
                                         `reply_media_url` VARCHAR(1024) COMMENT '回复的媒体 URL',
                                         `reply_title` VARCHAR(255) COMMENT '回复的标题',
                                         `reply_description` VARCHAR(255) COMMENT '回复的描述',
                                         `reply_thumb_media_id` VARCHAR(255) COMMENT '回复的缩略图的媒体 id',
                                         `reply_thumb_media_url` VARCHAR(1024) COMMENT '回复的缩略图的媒体 URL',
                                         `reply_articles` TEXT COMMENT '回复的图文消息数组',
                                         `reply_music_url` VARCHAR(1024) COMMENT '回复的音乐链接',
                                         `reply_hq_music_url` VARCHAR(1024) COMMENT '回复的高质量音乐链接',
                                         `creator` VARCHAR(64) DEFAULT '' COMMENT '创建者',
                                         `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                         `updater` VARCHAR(64) DEFAULT '' COMMENT '更新者',
                                         `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                         `deleted` BIT(1) NOT NULL DEFAULT FALSE COMMENT '是否删除',
                                         PRIMARY KEY (`id`)
) COMMENT '公众号菜单';


CREATE TABLE IF NOT EXISTS `mp_auto_reply` (
                                               `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
                                               `account_id` BIGINT NOT NULL COMMENT '公众号账号的编号',
                                               `app_id` VARCHAR(255) NOT NULL COMMENT '公众号 appId',
                                               `type` INT NOT NULL COMMENT '回复类型',
                                               `request_keyword` VARCHAR(255) COMMENT '请求的关键字',
                                               `request_match` INT COMMENT '请求的关键字的匹配',
                                               `request_message_type` VARCHAR(50) COMMENT '请求的消息类型',
                                               `response_message_type` VARCHAR(50) NOT NULL COMMENT '回复的消息类型',
                                               `response_content` TEXT COMMENT '回复的消息内容',
                                               `response_media_id` VARCHAR(255) COMMENT '回复的媒体 id',
                                               `response_media_url` VARCHAR(1024) COMMENT '回复的媒体 URL',
                                               `response_title` VARCHAR(255) COMMENT '回复的标题',
                                               `response_description` VARCHAR(255) COMMENT '回复的描述',
                                               `response_thumb_media_id` VARCHAR(255) COMMENT '回复的缩略图的媒体 id',
                                               `response_thumb_media_url` VARCHAR(1024) COMMENT '回复的缩略图的媒体 URL',
                                               `response_articles` TEXT COMMENT '回复的图文消息',
                                               `response_music_url` VARCHAR(1024) COMMENT '回复的音乐链接',
                                               `response_hq_music_url` VARCHAR(1024) COMMENT '回复的高质量音乐链接',
                                               `creator` VARCHAR(64) DEFAULT '' COMMENT '创建者',
                                               `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                               `updater` VARCHAR(64) DEFAULT '' COMMENT '更新者',
                                               `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                               `deleted` BIT(1) NOT NULL DEFAULT FALSE COMMENT '是否删除',
                                               PRIMARY KEY (`id`)
) COMMENT '公众号消息自动回复';



CREATE TABLE IF NOT EXISTS `mp_message` (
                                            `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
                                            `msg_id` BIGINT COMMENT '微信公众号消息 id',
                                            `account_id` BIGINT NOT NULL COMMENT '公众号账号的 ID',
                                            `app_id` VARCHAR(255) NOT NULL COMMENT '公众号 appid',
                                            `user_id` BIGINT COMMENT '公众号粉丝的编号',
                                            `openid` VARCHAR(255) COMMENT '公众号粉丝标志',
                                            `type` VARCHAR(50) NOT NULL COMMENT '消息类型',
                                            `send_from` INT NOT NULL COMMENT '消息来源',
                                            `content` TEXT COMMENT '消息内容',
                                            `media_id` VARCHAR(255) COMMENT '媒体文件的编号',
                                            `media_url` VARCHAR(1024) COMMENT '媒体文件的 URL',
                                            `recognition` TEXT COMMENT '语音识别后文本',
                                            `format` VARCHAR(50) COMMENT '语音格式',
                                            `title` VARCHAR(255) COMMENT '标题',
                                            `description` VARCHAR(255) COMMENT '描述',
                                            `thumb_media_id` VARCHAR(255) COMMENT '缩略图的媒体 id',
                                            `thumb_media_url` VARCHAR(1024) COMMENT '缩略图的媒体 URL',
                                            `url` VARCHAR(1024) COMMENT '点击图文消息跳转链接',
                                            `location_x` DOUBLE COMMENT '地理位置纬度',
                                            `location_y` DOUBLE COMMENT '地理位置经度',
                                            `scale` DOUBLE COMMENT '地图缩放大小',
                                            `label` VARCHAR(255) COMMENT '详细地址',
                                            `articles` TEXT COMMENT '图文消息数组',
                                            `music_url` VARCHAR(1024) COMMENT '音乐链接',
                                            `hq_music_url` VARCHAR(1024) COMMENT '高质量音乐链接',
                                            `event` VARCHAR(50) COMMENT '事件类型',
                                            `event_key` VARCHAR(255) COMMENT '事件 Key',
                                            `creator` VARCHAR(64) DEFAULT '' COMMENT '创建者',
                                            `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                            `updater` VARCHAR(64) DEFAULT '' COMMENT '更新者',
                                            `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                            `deleted` BIT(1) NOT NULL DEFAULT FALSE COMMENT '是否删除',
                                            PRIMARY KEY (`id`)
) COMMENT '公众号消息';

CREATE TABLE IF NOT EXISTS `mp_tag` (
                                        `id` BIGINT NOT NULL COMMENT '主键',
                                        `tag_id` BIGINT NOT NULL COMMENT '公众号标签 id',
                                        `name` VARCHAR(255) NOT NULL COMMENT '标签名',
                                        `count` INT COMMENT '此标签下粉丝数',
                                        `account_id` BIGINT NOT NULL COMMENT '公众号账号的编号',
                                        `app_id` VARCHAR(255) NOT NULL COMMENT '公众号 appId',
                                        `creator` VARCHAR(64) DEFAULT '' COMMENT '创建者',
                                        `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                        `updater` VARCHAR(64) DEFAULT '' COMMENT '更新者',
                                        `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                        `deleted` BIT(1) NOT NULL DEFAULT FALSE COMMENT '是否删除',
                                        PRIMARY KEY (`id`)
) COMMENT '公众号标签';


CREATE TABLE IF NOT EXISTS `mp_user` (
                                         `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '编号',
                                         `openid` VARCHAR(255) NOT NULL COMMENT '粉丝标识',
                                         `union_id` VARCHAR(255) COMMENT '微信生态唯一标识',
                                         `subscribe_status` INT NOT NULL COMMENT '关注状态',
                                         `subscribe_time` DATETIME COMMENT '关注时间',
                                         `unsubscribe_time` DATETIME COMMENT '取消关注时间',
                                         `nickname` VARCHAR(255) COMMENT '昵称',
                                         `head_image_url` VARCHAR(1024) COMMENT '头像地址',
                                         `language` VARCHAR(50) COMMENT '语言',
                                         `country` VARCHAR(255) COMMENT '国家',
                                         `province` VARCHAR(255) COMMENT '省份',
                                         `city` VARCHAR(255) COMMENT '城市',
                                         `remark` VARCHAR(255) COMMENT '备注',
                                         `tag_ids` TEXT COMMENT '标签编号数组',
                                         `account_id` BIGINT NOT NULL COMMENT '公众号账号的编号',
                                         `app_id` VARCHAR(255) NOT NULL COMMENT '公众号 appId',
                                         `creator` VARCHAR(64) DEFAULT '' COMMENT '创建者',
                                         `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                         `updater` VARCHAR(64) DEFAULT '' COMMENT '更新者',
                                         `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                         `deleted` BIT(1) NOT NULL DEFAULT FALSE COMMENT '是否删除',
                                         PRIMARY KEY (`id`),
                                         UNIQUE KEY `uniq_openid` (`openid`) COMMENT '粉丝标识唯一索引'
) COMMENT '公众号粉丝';