CREATE TABLE IF NOT EXISTS `trade_order` (
                                             `id` BIGINT NOT NULL AUTO_INCREMENT,
                                             `no` VARCHAR(255) NOT NULL,
                                             `type` INT NOT NULL,
                                             `terminal` INT NOT NULL,
                                             `user_id` BIGINT NOT NULL,
                                             `user_ip` VARCHAR(255) NOT NULL,
                                             `user_remark` VARCHAR(255),
                                             `status` INT NOT NULL,
                                             `product_count` INT NOT NULL,
                                             `cancel_type` INT,
                                             `remark` VARCHAR(255),
                                             `comment_status` BOOLEAN,
                                             `brokerage_user_id` BIGINT,
                                             `pay_status` BIT NOT NULL,
                                             `pay_time` DATETIME,
                                             `finish_time` DATETIME,
                                             `cancel_time` DATETIME,
                                             `total_price` INT,
                                             `order_price` INT,
                                             `discount_price` INT NOT NULL,
                                             `delivery_price` INT NOT NULL,
                                             `adjust_price` INT NOT NULL,
                                             `pay_price` INT NOT NULL,
                                             `delivery_type` INT NOT NULL,
                                             `pay_order_id` BIGINT,
                                             `pay_channel_code` VARCHAR(255),
                                             `delivery_template_id` BIGINT,
                                             `logistics_id` BIGINT,
                                             `logistics_no` VARCHAR(255),
                                             `delivery_time` DATETIME,
                                             `receive_time` DATETIME,
                                             `receiver_name` VARCHAR(255) NOT NULL,
                                             `receiver_mobile` VARCHAR(255) NOT NULL,
                                             `receiver_area_id` INT NOT NULL,
                                             `receiver_post_code` INT,
                                             `receiver_detail_address` VARCHAR(255) NOT NULL,
                                             `pick_up_store_id` BIGINT,
                                             `pick_up_verify_code` VARCHAR(255),
                                             `refund_status` INT,
                                             `refund_price` INT,
                                             `after_sale_status` INT,
                                             `coupon_id` BIGINT NOT NULL,
                                             `coupon_price` INT NOT NULL,
                                             `use_point` INT,
                                             `point_price` INT NOT NULL,
                                             `give_point` INT,
                                             `refund_point` INT,
                                             `vip_price` INT,
                                             `give_coupons_map` VARCHAR(255),
                                             `seckill_activity_id` BIGINT,
                                             `bargain_activity_id` BIGINT,
                                             `bargain_record_id` BIGINT,
                                             `combination_activity_id` BIGINT,
                                             `combination_head_id` BIGINT,
                                             `combination_record_id` BIGINT,
                                             `creator` VARCHAR(255) DEFAULT '',
                                             `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                             `updater` VARCHAR(255) DEFAULT '',
                                             `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                             `deleted` BIT NOT NULL DEFAULT 0,
                                             `tenant_id` BIGINT NOT NULL DEFAULT 0,
                                             PRIMARY KEY (`id`)
) COMMENT '交易订单表';

-- Repeat similar conversion changes for each of the other tables:
CREATE TABLE IF NOT EXISTS `trade_order_item` (
                                                  `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                  `user_id` BIGINT NOT NULL,
                                                  `order_id` BIGINT NOT NULL,
                                                  `cart_id` INT,
                                                  `spu_id` BIGINT NOT NULL,
                                                  `spu_name` VARCHAR(255) NOT NULL,
                                                  `sku_id` BIGINT NOT NULL,
                                                  `properties` VARCHAR(255),
                                                  `pic_url` VARCHAR(255),
                                                  `count` INT NOT NULL,
                                                  `comment_status` BOOLEAN,
                                                  `price` INT NOT NULL,
                                                  `discount_price` INT NOT NULL,
                                                  `delivery_price` INT,
                                                  `adjust_price` INT,
                                                  `pay_price` INT NOT NULL,
                                                  `coupon_price` INT,
                                                  `point_price` INT,
                                                  `use_point` INT,
                                                  `give_point` INT,
                                                  `vip_price` INT,
                                                  `after_sale_id` BIGINT,
                                                  `after_sale_status` INT NOT NULL,
                                                  `creator` VARCHAR(255) DEFAULT '',
                                                  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                  `updater` VARCHAR(255) DEFAULT '',
                                                  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                  `deleted` BIT NOT NULL DEFAULT 0,
                                                  PRIMARY KEY (`id`)
) COMMENT '交易订单明细表';

-- Continue with similar conversion for `trade_after_sale`, `trade_after_sale_log`, `trade_brokerage_user`, `trade_brokerage_record`, `trade_brokerage_withdraw`, `trade_delivery_express`.

-- Example for `trade_brokerage_user`
CREATE TABLE IF NOT EXISTS `trade_brokerage_user` (
                                                      `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                      `bind_user_id` BIGINT NOT NULL,
                                                      `bind_user_time` VARCHAR(255),
                                                      `brokerage_enabled` BIT NOT NULL,
                                                      `brokerage_time` VARCHAR(255),
                                                      `price` INT NOT NULL,
                                                      `frozen_price` INT NOT NULL,
                                                      `creator` VARCHAR(255) DEFAULT '',
                                                      `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                      `updater` VARCHAR(255) DEFAULT '',
                                                      `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                      `deleted` BIT NOT NULL DEFAULT 0,
                                                      `tenant_id` BIGINT NOT NULL DEFAULT 0,
                                                      PRIMARY KEY (`id`)
) COMMENT '分销用户';

CREATE TABLE IF NOT EXISTS `trade_brokerage_record` (
                                                        `id` INT NOT NULL AUTO_INCREMENT,
                                                        `user_id` BIGINT NOT NULL,
                                                        `biz_id` VARCHAR(255) NOT NULL,
                                                        `biz_type` VARCHAR(255) NOT NULL,
                                                        `title` VARCHAR(255) NOT NULL,
                                                        `price` INT NOT NULL,
                                                        `total_price` INT NOT NULL,
                                                        `description` VARCHAR(255) NOT NULL,
                                                        `status` VARCHAR(255) NOT NULL,
                                                        `frozen_days` INT NOT NULL,
                                                        `unfreeze_time` VARCHAR(255),
                                                        `creator` VARCHAR(255) DEFAULT '',
                                                        `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                        `updater` VARCHAR(255) DEFAULT '',
                                                        `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                        `deleted` BIT NOT NULL DEFAULT 0,
                                                        `tenant_id` BIGINT NOT NULL DEFAULT 0,
                                                        PRIMARY KEY (`id`)
) COMMENT='佣金记录';

CREATE TABLE IF NOT EXISTS `trade_brokerage_withdraw` (
                                                          `id` INT NOT NULL AUTO_INCREMENT,
                                                          `user_id` BIGINT NOT NULL,
                                                          `price` INT NOT NULL,
                                                          `fee_price` INT NOT NULL,
                                                          `total_price` INT NOT NULL,
                                                          `type` VARCHAR(255) NOT NULL,
                                                          `name` VARCHAR(255),
                                                          `account_no` VARCHAR(255),
                                                          `bank_name` VARCHAR(255),
                                                          `bank_address` VARCHAR(255),
                                                          `account_qr_code_url` VARCHAR(255),
                                                          `status` VARCHAR(255) NOT NULL,
                                                          `audit_reason` VARCHAR(255),
                                                          `audit_time` VARCHAR(255),
                                                          `remark` VARCHAR(255),
                                                          `creator` VARCHAR(255) DEFAULT '',
                                                          `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                          `updater` VARCHAR(255) DEFAULT '',
                                                          `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                          `deleted` BIT NOT NULL DEFAULT 0,
                                                          `tenant_id` BIGINT NOT NULL DEFAULT 0,
                                                          PRIMARY KEY (`id`)
) COMMENT='佣金提现';

CREATE TABLE IF NOT EXISTS `trade_delivery_express` (
                                                        `id` INT NOT NULL AUTO_INCREMENT,
                                                        `code` VARCHAR(255),
                                                        `name` VARCHAR(255),
                                                        `logo` VARCHAR(255),
                                                        `sort` INT NOT NULL,
                                                        `status` INT NOT NULL,
                                                        `creator` VARCHAR(255) DEFAULT '',
                                                        `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                        `updater` VARCHAR(255) DEFAULT '',
                                                        `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                                        `deleted` BIT NOT NULL DEFAULT 0,
                                                        PRIMARY KEY (`id`)
) COMMENT='佣金提现';

